name: AWS Lambda Package and Deploy

on:
  workflow_run:
    workflows: [ "Python Lint" ]
    branches: [ main ]
    types:
      - completed

jobs:
  package:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Package AWS Lambda
      run: make bundle-lambda-function-zip
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: expense-category-poster
        path: ./expense-category-poster.zip
        retention-days: 2
  deploy:
    runs-on: ubuntu-latest
    needs: package
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          role-duration-seconds: 1200
          role-session-name: LambdaDeployWorkflowSession
      - name: Download archived artifact
        uses: actions/download-artifact@v3
        with:
          name: expense-category-poster
      - name: AWS Lambda Deploy
        run: |
          aws lambda update-function-code --function-name expense-category-poster \
          --zip-file fileb://expense-category-poster.zip
      - name: Sleep for 20 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'
      - name: AWS Lambda Update
        run: |
          aws lambda update-function-configuration --function-name expense-category-poster \
          --handler main.lambda_handler \
          --layers arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p39-boto3:12